### ISSUE TITLE
training and testing codes

### ISSUE THREAD

**Issue by GrassBro** [google-research-datasets/hiertext#1]
Hi, @qinbbbb,

I see your network is also a novel trying with great performance. Do you have a plan to release the detailed codes about them?

**Comment by qinbbbb** [comment]
Yes, we plan to release the training code later this year.

**Comment by GrassBro** [comment]
> Yes, we plan to release the training code later this year.

Thanks. Looking forward to it being released sooner.

**Comment by qinbbbb** [comment]
Thanks for your interests. I will close the issue for now.

**Comment by longshangbang** [comment]
It's now released: https://github.com/tensorflow/models/tree/master/official/projects/unified_detector
