### ISSUE TITLE
Masks to Polygons code

### ISSUE THREAD

**Issue by bely66** [google-research-datasets/hiertext#11]
Hi Everyone, 
It seems you're using a special mask shape, however I want to get polygons from the masks.
is there any code to help with that?

**Comment by longshangbang** [comment]
what mask shapes are you referring to? Can you be more specific?

**Comment by bely66** [comment]
I'm trying to convert the labels of the word level annotations from masks to polygons (4 point polygon), all the annotations are masks

**Comment by longshangbang** [comment]
cv2.minarearect is what you need
