### ISSUE TITLE
how to do the evaluation of line-based unified detector?

### ISSUE THREAD

**Issue by sword-shadow** [google-research-datasets/hiertext#13]
Hi, thanks for your great work, 
In the related paper Towards End-to-End Unified Scene Text Detection and Layout Analysis, it mentioned the evaluation of line-based detector in Table 3. However, the code here can only handle detected word vertices in word, line and paragraph levels.  
To achieve the evaluation of line-based detector, should we just set the 'vertices' of 'word' as the detected line vertices in output Json file?

**Comment by longshangbang** [comment]
As explained in the unified detector post, by "line based", it means the detector generate a set of masks where each corresponds to one text line. Taking the connected components, we get pseudo words that are stored as polygons.
