### ISSUE TITLE
metric problem

### ISSUE THREAD

**Issue by MelosY** [google-research-datasets/hiertext#15]
Could you please report the precision,recall of word detection and paragraph detection in paper "Towards End-to-End Unified Scene Text Detection and Layout Analysis"?

**Comment by longshangbang** [comment]
Sure:
paragraph: (P/R/F/Tightness/PQ) 76.04, 62.45, 68.58, 78.17, 53.60

word: 69.57, 82.68, 75.56, 78.04, 58.97

**Comment by MelosY** [comment]
Sorry to bother you again，Could you please report the precision,recall，pq of word detection ,line and paragraph detection on validation set？

**Comment by longshangbang** [comment]
Sure! Happy to help.

It's actually right in this repo: https://github.com/google-research-datasets/hiertext#sample-output-on-the-validation-set
