### ISSUE TITLE
Share on Hugging Face ?

### ISSUE THREAD

**Issue by lhoestq** [google-research-datasets/hiertext#18]
Hi ! I'm Quentin from HF 🤗

Thanks for building this dataset, it's a really nice one !
I was wondering if you had any plan to share it on Hugging Face ?

This would let the community explore the data and and load it in one line or code. I believe it can have a nice impact and make it easier for researchers to train OCR models with this dataset :)

**Comment by longshangbang** [comment]
Hi Quentin, thanks for the request!

The images of the dataset are only hosted on CVDF. We are unfortunately unable to upload the images to Huggingface.
