### ISSUE TITLE
fatal error: An error occurred (404) when calling the HeadObject operation: Key "ocr/train.tgz" does not exist

### ISSUE THREAD

**Issue by Mountchicken** [google-research-datasets/hiertext#2]
### Problem Description
when running `aws s3 --no-sign-request cp s3://open-images-dataset/ocr/train.tgz .`, an error occurs `fatal error: An error occurred (404) when calling the HeadObject operation: Key "ocr/train.tgz" does not exist`

**Comment by longshangbang** [comment]
Hi, 

Could you try to reproduce this problem by running the command again on the same or a different machine? I just tried it on my own PC and it worked.

Additionally, could you try to use a VPN?

**Comment by Mountchicken** [comment]
I'm running this command on a cluster with aws version 1.3. which could be a problem. BTW, the cluster may not support VPN. Will you upload the dataset to Google Drive in the future? It would be easier to download.

**Comment by longshangbang** [comment]
That could be a problem. 
You can verify by trying to download the original open images datasets. They are also hosted on s3.

Currently, there's no plan to upload to Google Drive.
