### ISSUE TITLE
Doubts about subsection 4.1 of the paper.

### ISSUE THREAD

**Issue by willpat1213** [google-research-datasets/hiertext#3]
Problem solved, thanks a lot.

**Comment by Willpat1213** [comment]
> ![G9LIQ3LC`_A5Y4}2L0@DL}4](https://user-images.githubusercontent.com/69834766/166431751-489df0ee-34c6-4e86-a93b-45e1aa9240a0.png) What does t_c mean in the figure? Isn't the threshold represented by t_m in this subsection?



> ![G9LIQ3LC`_A5Y4}2L0@DL}4](https://user-images.githubusercontent.com/69834766/166431751-489df0ee-34c6-4e86-a93b-45e1aa9240a0.png) What does t_c mean in the figure? Isn't the threshold represented by t_m in this subsection?
