### ISSUE TITLE
Unified Detector, Error Message during Inference

### ISSUE THREAD

**Issue by bozcomlekci** [google-research-datasets/hiertext#5]
Greetings,

I'm trying to perform inference on the HierText dataset with Unified Detector. When I ran the inference script, I got the error message in the image.

The script I ran was:

```
python3 -m official.projects.unified_detector.run_inference \
--gin_file=official/projects/unified_detector/configs/gin_files/unified_detector_model.gin \
--ckpt_path=vision_unified_detector_unified_detector_ckpt \
--img_dir=<the-directory-containing-validation-images> \
--output_path=<some-directory>/validation_output.jsonl
```
The error message:
![error_message](https://user-images.githubusercontent.com/25280655/182360580-2b9b7ec2-2a02-48ca-a2ac-ead6a27bd9c9.png)

I'm utilizing an anaconda environment with Python3.7.13.  Initially, I ran [the scripts under the sections, "Set up TensorFlow Models" and  "Set up DeepLab2"](https://github.com/tensorflow/models/tree/master/official/projects/unified_detector). I installed [protoc with conda](https://anaconda.org/anaconda/protobuf). Finally, I downloaded the Unified-Detector-Line checkpoint file, decompressed the file with gzip, moved it to the "models" folder and ran the script above.

Could you help with the error message? I suspect that there is a mismatch in the packages installed, or the checkpoint file is broken.

Could you also specify which python version you are using the Unified Detector with?

Thanks in advance.

**Comment by longshangbang** [comment]
You need to specify the checkpoint up to the prefix of the files:

--ckpt_path=vision_unified_detector_unified_detector_ckpt/ckpt

**Comment by bozcomlekci** [comment]
Thanks, the problem was the extension of the downloaded checkpoint file is `.gz` but it has to be `.tar.gz` to extract it. I had to manually change it to `.tar.gz`, then extract it.  Although it is a small issue, it is confusing.
