### ISSUE TITLE
Empty paragraphs

### ISSUE THREAD

**Issue by Asafgendler** [google-research-datasets/hiertext#8]
Hello and thanks for the great dataset.

I hove noticed that the data contains a lot of empty paragraphs, meaning, paragraphs that do not have any lines or words inside them but do have a defining polygon.

I would really appreciate if you can explain what is the meaning of those paragraph objects.

Thanks,

**Comment by longshangbang** [comment]
Can you point me to the image IDs?

Also, as noted in the README:    "legible": true,  // If false, the region defined by `vertices` are considered as do-not-care in paragraph level evaluation.

What are the "legible" fields of them?

**Comment by Asafgendler** [comment]
They do no have any legible field as their only field is the vertices field, just wondered the reason for those paragraphs existence

**Comment by longshangbang** [comment]
They represent text regions that are highly illegible and should be ignored in paragraph evaluation.

**Comment by Asafgendler** [comment]
OK thanks, are all the not legible entities not used during training as well?

**Comment by longshangbang** [comment]
Lines/words are used. Illegible paragraphs are masked. Please refer to the code.

**Comment by Asafgendler** [comment]
Thanks
