### ISSUE TITLE
"vertices" fields in the paragraphs and lines level

### ISSUE THREAD

**Issue by Asafgendler** [google-research-datasets/hiertext#9]
Hello and thanks for the great dataset again.

I wanted to ask when do you use the "vertices" fields in the paragraphs and lines level.

In your paper and repo you describe the line and paragraph level bounding polygon as the union of their contained words polygon, so it made me wonder if their "vertices" field is ever used.

**Comment by longshangbang** [comment]
It's not used in the paper. The unified detector is a pure segmentation model.

**Comment by Asafgendler** [comment]
Thank you very much
